name: CI
on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Create Pull Request
      if: startsWith(github.ref, 'refs/tags/')
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.TOKEN }}
        commit-message: "chore: release ${{ github.ref_name }}"
        title: "Release ${{ github.ref_name }}"
        body: |
          Automated PR for release ${{ github.ref_name }}
        branch: release/${{ github.ref_name }}
        base: master
        
    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}